/************************************************************
*	INPUT PRODUCT PRICES WITH TAX							*
*	Version:	1.0.7										*
*	Date:		16.3.2014									*
*	File:		admin/view/javascript/price_with_tax.js		*
*	Author:		HydeNet										*
*	Web:		www.hydenet.fi								*
*	Email:		info@hydenet.fi								*
************************************************************/
$(document).ready(function(){var b=$("input[name='price']").val();var a=$("select[name='tax_class_id']").find(":selected").attr("title");$("input[name='price_w_tax']").val((b*(a/100+1)).toFixed(2));$("input[name*='\\[price\\]']").each(function(e){var c=$(this).attr("name").replace("[price]","[price_w_tax]");var f=$(this).attr("size");var d=($(this).val()*(a/100+1)).toFixed(2);$(this).after('&nbsp;<input type="text" name="'+c+'" value="'+d+'" size="'+f+'" />')});$("input[name='price']").live("keyup",function(e){var d=$("input[name='price']").val();var c=$("select[name='tax_class_id']").find(":selected").attr("title");$("input[name='price_w_tax']").val((d*(c/100+1)).toFixed(2))});$("input[name$='\\[price\\]']").live("keyup",function(f){var c=$(this).attr("name").replace("[price]","[price_w_tax]");var e=$(this).val();var d=$("select[name='tax_class_id']").find(":selected").attr("title");$("input[name='"+c+"']").val((e*(d/100+1)).toFixed(2))});$("input[name='price_w_tax']").live("keyup",function(e){var d=$("input[name='price_w_tax']").val();var c=$("select[name='tax_class_id'] option:selected").attr("title");$("input[name='price']").val((d/(c/100+1)).toFixed(4))});$("input[name$='\\[price_w_tax\\]']").live("keyup",function(f){var c=$(this).attr("name").replace("[price_w_tax]","[price]");var e=$(this).val();var d=$("select[name='tax_class_id']").find(":selected").attr("title");$("input[name='"+c+"']").val((e/(d/100+1)).toFixed(4))});$("select[name='tax_class_id']").change(function(){var d=$("input[name='price_w_tax']").val();var c=$("select[name='tax_class_id']").find(":selected").attr("title");$("input[name='price']").val((d/(c/100+1)).toFixed(4));$("input[name$='\\[price\\]']").each(function(f){var e=$(this).attr("name").replace("[price]","[price_w_tax]");var g=$("input[name='"+e+"']").val();$(this).val((g/(c/100+1)).toFixed(4))})})});