<?php  
class ControllerCommonPopup extends Controller {
	protected function index() {if (file_exists(DIR_TEMPLATE . $this->config->get('config_template') . '/template/common/popup.tpl')) { $this->template = $this->config->get('config_template') . '/template/common/popup.tpl';} else { $this->template = 'default/template/common/popup.tpl';}$this->render();}public function popupContent() {
	$id = $this->config->get('config_language_id');$this->load->model('tool/popup');$popup = $this->model_tool_popup->getData($id);$this->data['locations'] = array('Bottom-left','Bottom-right','Bottom-center','Top-left','Top-right','Top-center','Middle-left','Middle-right');$json = array();
	if($popup){ $popup['left'] = html_entity_decode($popup['left']); if($popup['width'] == 0) { $popup['width'] = '220'; }if($popup['height'] == 0) {$popup['height'] = '160';}
	$this->load->model('tool/image');if($popup['image']){$popup['thumb'] = $this->model_tool_image->resize($popup['image'], $popup['width'], $popup['height']);}$popup['loc'] = $this->data['locations'][$popup['loc']];$json['data'] = $popup;}$this->response->setOutput(json_encode($json));}public function popupdynamic() {
	$id = $this->config->get('config_language_id');$this->load->model('tool/popup');$popup = $this->model_tool_popup->getDynamic($id);$themes = array('theme1','theme2','theme3','theme4','theme5','theme6','theme7','theme8','theme9','theme10','theme11','theme12');$styles = array('bt','tb','lr','rl'); $json = array();
	if(!empty($popup)){$popup['theme'] = $themes[$popup['theme']];$popup['style'] = $styles[$popup['style']];$popup['url'] = str_replace('amp;', '', $popup['url']);$json['data'] = $popup;}$this->response->setOutput(json_encode($json));}public function popupnews() {if (isset($this->request->server['HTTPS']) && (($this->request->server['HTTPS'] == 'on') || ($this->request->server['HTTPS'] == '1'))) {$server = $this->config->get('config_ssl');} else {$server = $this->config->get('config_url');}
	$id = $this->config->get('config_language_id');if ($this->config->get('config_logo') && file_exists(DIR_IMAGE . $this->config->get('config_logo'))) {$logo = $server . 'image/' . $this->config->get('config_logo');} else {$logo = '';}$json = array();$this->load->model('tool/popup');$popup = $this->model_tool_popup->getNews($id);$themes = array('themenews1','themenews2','themenews3','themenews4','themenews5','themenews6','themenews7','themenews8','themenews9','themenews10','themenews11','themenews12');if(!empty($popup)){$popup['theme'] = $themes[$popup['theme']];if($popup['width'] == 0) {$popup['width'] = '220';}if($popup['height'] == 0) {$popup['height'] = '40';}$this->load->model('tool/image');if($popup['image']){$popup['thumb'] = $this->model_tool_image->resize($popup['image'], $popup['width'], $popup['height']);}$popup['logosrc'] = str_replace(" ","%20", $logo);$json = $popup;}$this->response->setOutput(json_encode($json));}public function popupnewsdata() {$this->load->model('tool/popup');$popup = $this->model_tool_popup->submitData($this->request->post);if($popup){setcookie('popupnews','1',time() + (10 * 365 * 24 * 60 * 60));}$this->response->setOutput(json_encode($popup));}
}
?>